require('dotenv').config({
    path: require('path').resolve(__dirname, '../../.env')
});

const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({

    service: 'gmail',

    auth: {

        user: process.env.EMAIL_USER,

        pass: process.env.EMAIL_PASS

    }

});

async function sendAppointmentEmail(appointment) {

    try {

        if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {

            throw new Error(
                'Missing EMAIL_USER or EMAIL_PASS in medical-service/.env'
            );

        }

        const mailOptions = {

            from: process.env.EMAIL_USER,

            to: process.env.EMAIL_USER,

            subject: `Smart Clinic - New appointment with ${appointment.doctor}`,

            html: `

                <h2>Smart Clinic Notification</h2>

                <p>
                    A new medical appointment has been successfully created.
                </p>

                <h3>Appointment details:</h3>

                <ul>
                    <li><b>Patient ID:</b> ${appointment.patientId}</li>
                    <li><b>Doctor:</b> ${appointment.doctor}</li>
                    <li><b>Date:</b> ${appointment.date}</li>
                </ul>

                <p>
                    This email was automatically generated by the MCP Email AI Agent.
                </p>

                <br>

                <p>
                    Best regards,<br>
                    Smart Clinic Team
                </p>

            `
        };

        const info = await transporter.sendMail(mailOptions);

        console.log('AI email sent successfully');
        console.log(info.response);

    } catch (error) {

        console.log('EMAIL ERROR');
        console.log(error.message);

        throw error;
    }

}

module.exports = sendAppointmentEmail;